version: '3.3'
services:
  backend-app:
    build:
      context: .
      dockerfile: docker/Dockerfile-pi
    env_file:
      - .env
    #ports:
    #  - "8080:5000"
    volumes:
      - ./uploads:/uploads
    restart: always
    network_mode: host