version: '3.3'
services:
  backend-app:
    build:
      context: .
      dockerfile: docker/Dockerfile-pi
    env_file:
      - .env
    ports:
      - "8080:5000"
    networks:
      - your-network

networks:
  your-network: