FROM navikey/raspbian-bullseye:latest

WORKDIR /app

# Installiere Abhängigkeiten
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y python3 python3-pip python3-picamera2 gcc python3-dev libcap-dev \
    pkg-config libcups2-dev --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Kopiere nur die notwendigen Dateien zuerst, um Docker-Caching zu nutzen
COPY ./config /app/config
COPY ./samples /app/samples
COPY ./src /app/src
COPY ./tests /app/tests

COPY ./requirements.txt /app/

# Installiere Projekt-Abhängigkeiten # use poetry export --without-hashes --with prod > requirements.txt to create it
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

LABEL maintainer="Daniel Mueller <daniel.mueller@damu-analytics.com>"

# Setze den Ausführungsbefehl beim Containerstart
CMD ["flask", "--app", "src/frontend/flask_test", "run", "--host", "0.0.0.0"]
