FROM python:3.9.18

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y git gcc libffi-dev python3-dev && \
    rm -rf /var/lib/apt/lists/*
RUN apt-get install -y build-essential meson ninja-build pkg-config \
    g++ clang libyaml-dev python3-yaml python3-ply python3-jinja2 \
    libssl-dev openssl libdw-dev libunwind-dev libudev-dev  \
    libdrm-dev libjpeg-dev libsdl2-dev

RUN git clone https://git.libcamera.org/libcamera/libcamera.git && \
    cd libcamera

RUN meson build
RUN ninja-C build install -j4

RUN pip3 install picamera2

COPY ./hello-world.py /app/hello-world.py

CMD ["python3", "hello-world.py"]