FROM navikey/raspbian-bullseye:latest

WORKDIR /app

# Installiere Abhängigkeiten
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y python3 python3-pip
RUN pip install --upgrade pip
RUN apt install -y python3-picamera2 --no-install-recommends
RUN apt-get -y install gcc python3-dev libcups2-dev

# Kopiere nur die notwendigen Dateien zuerst, um Docker-Caching zu nutzen
COPY ./config /app/config
COPY ./samples /app/samples
COPY ./src /app/src
COPY ./tests /app/tests

COPY ./requirements.txt /app/

# Installiere Projekt-Abhängigkeiten # use poetry export --without-hashes --with prod > requirements.txt to create it
RUN pip install -r requirements.txt

# Setze den Ausführungsbefehl beim Containerstart
CMD ["flask", "--app", "src/frontend/flask_test", "run", "--host", "0.0.0.0"]
