FROM arm32v7/python:3.9

WORKDIR /app

# Installiere Abhängigkeiten
RUN apt-get update && apt-get -y install gcc python3-dev libcups2-dev

# Kopiere nur die notwendigen Dateien zuerst, um Docker-Caching zu nutzen
COPY ./pyproject.toml ./poetry.lock /app/
COPY ./config /app/config
COPY ./samples /app/samples
COPY ./src /app/src
COPY ./tests /app/tests

COPY ./requirements.txt /app/

# Installiere Projekt-Abhängigkeiten # use poetry export --without-hashes --with prod > requirements.txt to create it
RUN pip3 install -r requirements.txt

# Setze den Ausführungsbefehl beim Containerstart
CMD ["flask", "--app", "src/frontend/flask_test", "run", "--host", "0.0.0.0"]

