# some app_settings
texts:
  welcome_main_text: "Welcome on this Application"
  welcome_sub_text: "Click the Buzzer"
  layout_text_2: ""
  layout_text_3: ""

paths:
  layout_path: "samples/layouts"
  font_path: "fonts"

prompts:
  poem_prompt: "You are are poem writer. You see a picture from a party with happy people." \
  " Interprete the Picture and details you see. Write a Haiku about the picture."